name: lemonade-server
version: "9.1.3"
base: core24
summary: Local AI server with OpenAI-compatible API
title: Lemonade Server
description: |
  Lemonade Server is a lightweight, high-performance local AI inference server
  that provides an OpenAI-compatible API for running large language models on
  your own hardware.

  **Features:**
  - OpenAI-compatible REST API (chat completions, embeddings, etc.)
  - Multiple backend support: Vulkan, ROCm (AMD GPUs), and CPU
  - Automatic model management and caching
  - Support for GGUF models from Hugging Face
  - Low latency local inference
  - Runs as a background service

  **Supported Hardware:**
  - AMD GPUs: RDNA3 (RX 7000), RDNA4 (RX 9000), Strix Point/Halo APUs
  - Any Vulkan-capable GPU
  - CPU fallback for systems without GPU acceleration

  **Quick Start:**
  The server starts automatically after installation. Access the API at:
  http://localhost:8000/api/v1

  **ROCm Support (AMD GPUs):**
  For ROCm GPU acceleration, connect the process-control interface:
  sudo snap connect lemonade-server:process-control

  For status/metrics reporting, lemonade-server.metrics requires:
  sudo snap connect lemonade-server:system-observe

  **Documentation:** https://lemonade-server.ai/

adopt-info: lemonade-server
grade: stable
confinement: strict
license: MIT

website: https://lemonade-server.ai
source-code: https://github.com/lemonade-sdk/lemonade
issues: https://github.com/kenvandine/lemonade-server-snap/issues
contact: https://github.com/kenvandine/lemonade-server-snap/issues

platforms:
  amd64:

layout:
  /usr/local/share/lemonade-server:
    symlink: $SNAP/usr/local/share/lemonade-server

apps:
  metrics:
    command: bin/metrics
    plugs:
      - home
      - removable-media
      - network
      - network-bind
      - opengl
      - process-control
      - hardware-observe
      - system-observe
  lemonade-server:
    command: usr/local/bin/lemonade-server
    plugs:
      - home
      - removable-media
      - network
      - network-bind
      - opengl
    environment:
      LD_LIBRARY_PATH: "$SNAP/usr/local/share/lemonade-server:$SNAP/usr/local/lib/llamacpp/vulkan:$SNAP/usr/lib/x86_64-linux-gnu:$SNAP/lib/x86_64-linux-gnu:/var/lib/snapd/lib/gl${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
      PATH: "$SNAP/usr/local/bin:$PATH"
      LEMONADE_LLAMACPP_VULKAN_BIN: "$SNAP/usr/local/lib/llamacpp/vulkan/llama-server"
      LEMONADE_LLAMACPP_CPU_BIN: "$SNAP/usr/local/lib/llamacpp/cpu/llama-server"
      LEMONADE_LLAMACPP_ROCM_BIN: "$SNAP/usr/local/bin/llama-server-rocm"
  service:
    command: bin/lemonade-server-wrapper serve
    daemon: simple
    install-mode: enable
    restart-condition: on-failure
    refresh-mode: restart
    plugs:
      - home
      - removable-media
      - network
      - network-bind
      - opengl
      - process-control
      - hardware-observe
    environment:
      LD_LIBRARY_PATH: "$SNAP/usr/local/share/lemonade-server:$SNAP/usr/local/lib/llamacpp/vulkan:$SNAP/usr/lib/x86_64-linux-gnu:$SNAP/lib/x86_64-linux-gnu:/var/lib/snapd/lib/gl${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
      PATH: "$SNAP/usr/local/bin:$PATH"
      HOME: "$SNAP_COMMON"
      LEMONADE_CACHE_DIR: "$SNAP_COMMON/cache/lemonade"
      LEMONADE_LLAMACPP_VULKAN_BIN: "$SNAP/usr/local/lib/llamacpp/vulkan/llama-server"
      LEMONADE_LLAMACPP_CPU_BIN: "$SNAP/usr/local/lib/llamacpp/cpu/llama-server"
      LEMONADE_LLAMACPP_ROCM_BIN: "$SNAP/usr/local/bin/llama-server-rocm"

parts:
  deps:
    plugin: nil
    stage-packages:
      - libgomp1
      - libatomic1
      - libcurl4t64
      - curl # for metrics

  lemonade-server:
    plugin: dump
    source: https://github.com/lemonade-sdk/lemonade/releases/download/v$SNAPCRAFT_PROJECT_VERSION/lemonade-server-minimal_$SNAPCRAFT_PROJECT_VERSION_amd64.deb

  llamacpp-vulkan:
    plugin: nil
    source: https://github.com/ggml-org/llama.cpp/releases/download/b7744/llama-b7744-bin-ubuntu-vulkan-x64.zip
    source-type: zip
    override-build: |
      craftctl default
      mkdir -p $CRAFT_PART_INSTALL/usr/local/lib/llamacpp/vulkan
      DEST=$CRAFT_PART_INSTALL/usr/local/lib/llamacpp/vulkan
      # Copy all files
      cp -a build/bin/* $DEST/
      # Fix broken symlinks (zip stores them as text files with target name)
      cd $DEST
      for f in *.so *.so.[0-9]*; do
        if [ -f "$f" ] && [ $(stat -c%s "$f") -lt 200 ]; then
          target=$(cat "$f" 2>/dev/null | tr -d '\0')
          if [ -f "$target" ]; then
            rm "$f"
            ln -sf "$target" "$f"
          fi
        fi
      done
      chmod +x $DEST/llama-server
    stage-packages:
      - libvulkan1

  llamacpp-cpu:
    plugin: nil
    source: https://github.com/ggml-org/llama.cpp/releases/download/b7744/llama-b7744-bin-ubuntu-x64.zip
    source-type: zip
    override-build: |
      craftctl default
      mkdir -p $CRAFT_PART_INSTALL/usr/local/lib/llamacpp/cpu
      DEST=$CRAFT_PART_INSTALL/usr/local/lib/llamacpp/cpu
      cp -a build/bin/* $DEST/
      # Fix broken symlinks
      cd $DEST
      for f in *.so *.so.[0-9]*; do
        if [ -f "$f" ] && [ $(stat -c%s "$f") -lt 200 ]; then
          target=$(cat "$f" 2>/dev/null | tr -d '\0')
          if [ -f "$target" ]; then
            rm "$f"
            ln -sf "$target" "$f"
          fi
        fi
      done
      chmod +x $DEST/llama-server

  llamacpp-rocm-gfx110x:
    plugin: nil
    source: https://github.com/lemonade-sdk/llamacpp-rocm/releases/download/b1160/llama-b1160-ubuntu-rocm-gfx110X-x64.zip
    source-type: zip
    override-build: |
      craftctl default
      mkdir -p $CRAFT_PART_INSTALL/usr/local/lib/llamacpp/rocm/gfx110X
      DEST=$CRAFT_PART_INSTALL/usr/local/lib/llamacpp/rocm/gfx110X
      cp -a * $DEST/ || true
      cd $DEST
      for f in *.so *.so.[0-9]*; do
        if [ -f "$f" ] && [ $(stat -c%s "$f") -lt 200 ]; then
          target=$(cat "$f" 2>/dev/null | tr -d '\0')
          if [ -f "$target" ]; then
            rm "$f"
            ln -sf "$target" "$f"
          fi
        fi
      done
      chmod +x $DEST/llama-server

  llamacpp-rocm-gfx1150:
    plugin: nil
    source: https://github.com/lemonade-sdk/llamacpp-rocm/releases/download/b1160/llama-b1160-ubuntu-rocm-gfx1150-x64.zip
    source-type: zip
    override-build: |
      craftctl default
      mkdir -p $CRAFT_PART_INSTALL/usr/local/lib/llamacpp/rocm/gfx1150
      DEST=$CRAFT_PART_INSTALL/usr/local/lib/llamacpp/rocm/gfx1150
      cp -a * $DEST/ || true
      cd $DEST
      for f in *.so *.so.[0-9]*; do
        if [ -f "$f" ] && [ $(stat -c%s "$f") -lt 200 ]; then
          target=$(cat "$f" 2>/dev/null | tr -d '\0')
          if [ -f "$target" ]; then
            rm "$f"
            ln -sf "$target" "$f"
          fi
        fi
      done
      chmod +x $DEST/llama-server

  llamacpp-rocm-gfx1151:
    plugin: nil
    source: https://github.com/lemonade-sdk/llamacpp-rocm/releases/download/b1160/llama-b1160-ubuntu-rocm-gfx1151-x64.zip
    source-type: zip
    override-build: |
      craftctl default
      mkdir -p $CRAFT_PART_INSTALL/usr/local/lib/llamacpp/rocm/gfx1151
      DEST=$CRAFT_PART_INSTALL/usr/local/lib/llamacpp/rocm/gfx1151
      cp -a * $DEST/ || true
      cd $DEST
      for f in *.so *.so.[0-9]*; do
        if [ -f "$f" ] && [ $(stat -c%s "$f") -lt 200 ]; then
          target=$(cat "$f" 2>/dev/null | tr -d '\0')
          if [ -f "$target" ]; then
            rm "$f"
            ln -sf "$target" "$f"
          fi
        fi
      done
      chmod +x $DEST/llama-server

  llamacpp-rocm-gfx120x:
    plugin: nil
    source: https://github.com/lemonade-sdk/llamacpp-rocm/releases/download/b1160/llama-b1160-ubuntu-rocm-gfx120X-x64.zip
    source-type: zip
    override-build: |
      craftctl default
      mkdir -p $CRAFT_PART_INSTALL/usr/local/lib/llamacpp/rocm/gfx120X
      DEST=$CRAFT_PART_INSTALL/usr/local/lib/llamacpp/rocm/gfx120X
      cp -a * $DEST/ || true
      cd $DEST
      for f in *.so *.so.[0-9]*; do
        if [ -f "$f" ] && [ $(stat -c%s "$f") -lt 200 ]; then
          target=$(cat "$f" 2>/dev/null | tr -d '\0')
          if [ -f "$target" ]; then
            rm "$f"
            ln -sf "$target" "$f"
          fi
        fi
      done
      chmod +x $DEST/llama-server

  llamacpp-rocm-wrapper:
    plugin: nil
    after:
      - llamacpp-rocm-gfx110x
      - llamacpp-rocm-gfx1150
      - llamacpp-rocm-gfx1151
      - llamacpp-rocm-gfx120x
    stage-packages:
      - pciutils
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/usr/local/bin
      cat > $CRAFT_PART_INSTALL/usr/local/bin/llama-server-rocm << 'EOF'
      #!/bin/bash
      # Detect AMD GPU architecture and run the appropriate llama-server binary
      # Uses PCI device IDs since snap sandbox lacks the PCI ID database

      ROCM_BASE="$SNAP/usr/local/lib/llamacpp/rocm"
      ARCH="gfx110X"  # default

      # Detect GPU from lspci output - extract AMD device ID [1002:XXXX]
      GPU_LINE=$(lspci -nn 2>/dev/null | grep -iE "vga|display|3d" | grep -i "1002:" | head -1)

      if [ -n "$GPU_LINE" ]; then
        # Extract device ID (e.g., 150e from [1002:150e])
        DEVICE_ID=$(echo "$GPU_LINE" | grep -oE '\[1002:[0-9a-fA-F]+\]' | grep -oE ':[0-9a-fA-F]+' | tr -d ':' | tr '[:upper:]' '[:lower:]')

        case "$DEVICE_ID" in
          # Strix Point - gfx1150 (Radeon 880M/890M)
          150e|150f)
            ARCH="gfx1150"
            ;;
          # Strix Halo - gfx1151 (Radeon 8050S/8060S)
          1510|1511|1512)
            ARCH="gfx1151"
            ;;
          # RDNA4 - gfx120X (RX 9000 series)
          # Device IDs TBD - using pattern match as fallback
          *)
            # Fallback: try name-based detection if device ID not in list
            if echo "$GPU_LINE" | grep -qiE "8050S|8060S"; then
              ARCH="gfx1151"
            elif echo "$GPU_LINE" | grep -qiE "880M|890M"; then
              ARCH="gfx1150"
            elif echo "$GPU_LINE" | grep -qiE "9060|9070|R9700"; then
              ARCH="gfx120X"
            elif echo "$GPU_LINE" | grep -qiE "7700|7800|7900|V710|780M|760M"; then
              ARCH="gfx110X"
            fi
            ;;
        esac
      fi

      BINARY="$ROCM_BASE/$ARCH/llama-server"

      # Fallback to gfx110X if detected arch binary doesn't exist
      if [ ! -x "$BINARY" ]; then
        ARCH="gfx110X"
        BINARY="$ROCM_BASE/$ARCH/llama-server"
      fi

      # Set LD_LIBRARY_PATH for ROCm libraries
      export LD_LIBRARY_PATH="$ROCM_BASE/$ARCH:${LD_LIBRARY_PATH}"

      # Log detection for debugging
      echo "[ROCm Wrapper] Detected device ID: $DEVICE_ID, using architecture: $ARCH" >&2

      exec "$BINARY" "$@"
      EOF
      chmod +x $CRAFT_PART_INSTALL/usr/local/bin/llama-server-rocm

  scripts:
    plugin: dump
    source: scripts/
    organize:
      lemonade-server-wrapper: bin/lemonade-server-wrapper
      metrics: bin/metrics
    override-prime: |
      craftctl default
      chmod +x $CRAFT_PRIME/bin/lemonade-server-wrapper
      chmod +x $CRAFT_PRIME/bin/metrics
