name: lemonade-server
version: "9.1.3"
base: core24
summary: Lemonade
description: |
  Lemonade
adopt-info: lemonade
grade: stable
confinement: strict
license: MIT
platforms:
  amd64:

layout:
  /usr/local/share/lemonade-server:
    symlink: $SNAP/usr/local/share/lemonade-server

apps:
  lemonade-server:
    command: usr/local/bin/lemonade-server
    plugs:
      - home
      - removable-media
      - network
      - network-bind
      - opengl
    environment:
      LD_LIBRARY_PATH: "$SNAP/usr/local/share/lemonade-server:$SNAP/usr/local/lib/llamacpp/vulkan:$SNAP/usr/lib/x86_64-linux-gnu:$SNAP/lib/x86_64-linux-gnu:/var/lib/snapd/lib/gl${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
      PATH: "$SNAP/usr/local/bin:$PATH"
      LEMONADE_LLAMACPP_VULKAN_BIN: "$SNAP/usr/local/lib/llamacpp/vulkan/llama-server"
      LEMONADE_LLAMACPP_CPU_BIN: "$SNAP/usr/local/lib/llamacpp/cpu/llama-server"
      LEMONADE_LLAMACPP_ROCM_BIN: "$SNAP/usr/local/bin/llama-server-rocm"
  service:
    command: usr/local/bin/lemonade-server serve
    daemon: simple
    install-mode: enable
    restart-condition: on-failure
    refresh-mode: restart
    plugs:
      - home
      - removable-media
      - network
      - network-bind
      - opengl
    environment:
      LD_LIBRARY_PATH: "$SNAP/usr/local/share/lemonade-server:$SNAP/usr/local/lib/llamacpp/vulkan:$SNAP/usr/lib/x86_64-linux-gnu:$SNAP/lib/x86_64-linux-gnu:/var/lib/snapd/lib/gl${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
      PATH: "$SNAP/usr/local/bin:$PATH"
      HOME: "$SNAP_COMMON"
      LEMONADE_CACHE_DIR: "$SNAP_COMMON/cache/lemonade"
      LEMONADE_LLAMACPP_VULKAN_BIN: "$SNAP/usr/local/lib/llamacpp/vulkan/llama-server"
      LEMONADE_LLAMACPP_CPU_BIN: "$SNAP/usr/local/lib/llamacpp/cpu/llama-server"
      LEMONADE_LLAMACPP_ROCM_BIN: "$SNAP/usr/local/bin/llama-server-rocm"

parts:
  deps:
    plugin: nil
    stage-packages:
      - libgomp1
      - libatomic1
      - libcurl4t64

  lemonade-server:
    plugin: dump
    source: https://github.com/lemonade-sdk/lemonade/releases/download/v$SNAPCRAFT_PROJECT_VERSION/lemonade-server-minimal_$SNAPCRAFT_PROJECT_VERSION_amd64.deb

  llamacpp-vulkan:
    plugin: nil
    source: https://github.com/ggml-org/llama.cpp/releases/download/b7426/llama-b7426-bin-ubuntu-vulkan-x64.zip
    source-type: zip
    override-build: |
      craftctl default
      mkdir -p $CRAFT_PART_INSTALL/usr/local/lib/llamacpp/vulkan
      DEST=$CRAFT_PART_INSTALL/usr/local/lib/llamacpp/vulkan
      # Copy all files
      cp -a build/bin/* $DEST/
      # Fix broken symlinks (zip stores them as text files with target name)
      cd $DEST
      for f in *.so *.so.[0-9]*; do
        if [ -f "$f" ] && [ $(stat -c%s "$f") -lt 200 ]; then
          target=$(cat "$f" 2>/dev/null | tr -d '\0')
          if [ -f "$target" ]; then
            rm "$f"
            ln -sf "$target" "$f"
          fi
        fi
      done
      chmod +x $DEST/llama-server
    stage-packages:
      - libvulkan1

  llamacpp-cpu:
    plugin: nil
    source: https://github.com/ggml-org/llama.cpp/releases/download/b7426/llama-b7426-bin-ubuntu-x64.zip
    source-type: zip
    override-build: |
      craftctl default
      mkdir -p $CRAFT_PART_INSTALL/usr/local/lib/llamacpp/cpu
      DEST=$CRAFT_PART_INSTALL/usr/local/lib/llamacpp/cpu
      cp -a build/bin/* $DEST/
      # Fix broken symlinks
      cd $DEST
      for f in *.so *.so.[0-9]*; do
        if [ -f "$f" ] && [ $(stat -c%s "$f") -lt 200 ]; then
          target=$(cat "$f" 2>/dev/null | tr -d '\0')
          if [ -f "$target" ]; then
            rm "$f"
            ln -sf "$target" "$f"
          fi
        fi
      done
      chmod +x $DEST/llama-server

  llamacpp-rocm-gfx110x:
    plugin: nil
    source: https://github.com/lemonade-sdk/llamacpp-rocm/releases/download/b1136/llama-b1136-ubuntu-rocm-gfx110X-x64.zip
    source-type: zip
    override-build: |
      craftctl default
      mkdir -p $CRAFT_PART_INSTALL/usr/local/lib/llamacpp/rocm/gfx110X
      DEST=$CRAFT_PART_INSTALL/usr/local/lib/llamacpp/rocm/gfx110X
      cp -a * $DEST/ || true
      cd $DEST
      for f in *.so *.so.[0-9]*; do
        if [ -f "$f" ] && [ $(stat -c%s "$f") -lt 200 ]; then
          target=$(cat "$f" 2>/dev/null | tr -d '\0')
          if [ -f "$target" ]; then
            rm "$f"
            ln -sf "$target" "$f"
          fi
        fi
      done
      chmod +x $DEST/llama-server

  llamacpp-rocm-gfx1150:
    plugin: nil
    source: https://github.com/lemonade-sdk/llamacpp-rocm/releases/download/b1136/llama-b1136-ubuntu-rocm-gfx1150-x64.zip
    source-type: zip
    override-build: |
      craftctl default
      mkdir -p $CRAFT_PART_INSTALL/usr/local/lib/llamacpp/rocm/gfx1150
      DEST=$CRAFT_PART_INSTALL/usr/local/lib/llamacpp/rocm/gfx1150
      cp -a * $DEST/ || true
      cd $DEST
      for f in *.so *.so.[0-9]*; do
        if [ -f "$f" ] && [ $(stat -c%s "$f") -lt 200 ]; then
          target=$(cat "$f" 2>/dev/null | tr -d '\0')
          if [ -f "$target" ]; then
            rm "$f"
            ln -sf "$target" "$f"
          fi
        fi
      done
      chmod +x $DEST/llama-server

  llamacpp-rocm-gfx1151:
    plugin: nil
    source: https://github.com/lemonade-sdk/llamacpp-rocm/releases/download/b1136/llama-b1136-ubuntu-rocm-gfx1151-x64.zip
    source-type: zip
    override-build: |
      craftctl default
      mkdir -p $CRAFT_PART_INSTALL/usr/local/lib/llamacpp/rocm/gfx1151
      DEST=$CRAFT_PART_INSTALL/usr/local/lib/llamacpp/rocm/gfx1151
      cp -a * $DEST/ || true
      cd $DEST
      for f in *.so *.so.[0-9]*; do
        if [ -f "$f" ] && [ $(stat -c%s "$f") -lt 200 ]; then
          target=$(cat "$f" 2>/dev/null | tr -d '\0')
          if [ -f "$target" ]; then
            rm "$f"
            ln -sf "$target" "$f"
          fi
        fi
      done
      chmod +x $DEST/llama-server

  llamacpp-rocm-gfx120x:
    plugin: nil
    source: https://github.com/lemonade-sdk/llamacpp-rocm/releases/download/b1136/llama-b1136-ubuntu-rocm-gfx120X-x64.zip
    source-type: zip
    override-build: |
      craftctl default
      mkdir -p $CRAFT_PART_INSTALL/usr/local/lib/llamacpp/rocm/gfx120X
      DEST=$CRAFT_PART_INSTALL/usr/local/lib/llamacpp/rocm/gfx120X
      cp -a * $DEST/ || true
      cd $DEST
      for f in *.so *.so.[0-9]*; do
        if [ -f "$f" ] && [ $(stat -c%s "$f") -lt 200 ]; then
          target=$(cat "$f" 2>/dev/null | tr -d '\0')
          if [ -f "$target" ]; then
            rm "$f"
            ln -sf "$target" "$f"
          fi
        fi
      done
      chmod +x $DEST/llama-server

  llamacpp-rocm-wrapper:
    plugin: nil
    after:
      - llamacpp-rocm-gfx110x
      - llamacpp-rocm-gfx1150
      - llamacpp-rocm-gfx1151
      - llamacpp-rocm-gfx120x
    stage-packages:
      - pciutils
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/usr/local/bin
      cat > $CRAFT_PART_INSTALL/usr/local/bin/llama-server-rocm << 'EOF'
      #!/bin/bash
      # Detect AMD GPU architecture and run the appropriate llama-server binary

      ROCM_BASE="$SNAP/usr/local/lib/llamacpp/rocm"
      ARCH="gfx110X"  # default

      # Detect GPU from lspci output
      GPU_INFO=$(lspci -nn 2>/dev/null | grep -i "vga\|display\|3d" | grep -i "amd\|ati" | head -1)

      if [ -n "$GPU_INFO" ]; then
        # STX Halo detection (Radeon 8060S, etc.)
        if echo "$GPU_INFO" | grep -qiE "8060|8050|8040|strix.*halo"; then
          ARCH="gfx1151"
        # STX Point detection
        elif echo "$GPU_INFO" | grep -qiE "strix.*point"; then
          ARCH="gfx1150"
        # RDNA4 detection (RX 9xxx series)
        elif echo "$GPU_INFO" | grep -qiE "RX.?9[0-9]{3}|radeon.?9[0-9]{3}"; then
          ARCH="gfx120X"
        # RDNA3 detection (RX 7xxx series, 780M, 760M, etc.)
        elif echo "$GPU_INFO" | grep -qiE "RX.?7[0-9]{3}|7[0-9]{2}M|radeon.?7[0-9]{3}"; then
          ARCH="gfx110X"
        fi
      fi

      BINARY="$ROCM_BASE/$ARCH/llama-server"

      # Fallback to gfx110X if detected arch binary doesn't exist
      if [ ! -x "$BINARY" ]; then
        ARCH="gfx110X"
        BINARY="$ROCM_BASE/$ARCH/llama-server"
      fi

      # Set LD_LIBRARY_PATH for ROCm libraries
      export LD_LIBRARY_PATH="$ROCM_BASE/$ARCH:${LD_LIBRARY_PATH}"

      exec "$BINARY" "$@"
      EOF
      chmod +x $CRAFT_PART_INSTALL/usr/local/bin/llama-server-rocm
