name: lemonade-server
base: core24
summary: Local AI server with OpenAI-compatible API
title: Lemonade Server
description: |
  Lemonade Server is a lightweight, high-performance local AI inference server
  that provides an OpenAI-compatible API for running large language models on
  your own hardware.

  **Features:**
  - OpenAI-compatible REST API (chat completions, embeddings, etc.)
  - Multiple backend support: Vulkan, ROCm (AMD GPUs), and CPU
  - Automatic model management and caching
  - Support for GGUF models from Hugging Face
  - Low latency local inference
  - Runs as a background service

  **Supported Hardware:**
  - AMD GPUs: RDNA3 (RX 7000), RDNA4 (RX 9000), Strix Point/Halo APUs
  - Any Vulkan-capable GPU
  - CPU fallback for systems without GPU acceleration

  **Quick Start:**
  The server starts automatically after installation. Access the API at:
  http://localhost:8000/api/v1

  **ROCm Support (AMD GPUs):**
  For ROCm GPU acceleration, connect the process-control interface:
  sudo snap connect lemonade-server:process-control

  For status/metrics reporting, lemonade-server.metrics requires:
  sudo snap connect lemonade-server:system-observe

  **Documentation:** https://lemonade-server.ai/

adopt-info: lemonade-server
grade: stable
confinement: strict
license: Apache-2.0

website: https://lemonade-server.ai
source-code: https://github.com/lemonade-sdk/lemonade
issues: https://github.com/kenvandine/lemonade-server-snap/issues
contact: https://github.com/kenvandine/lemonade-server-snap/issues

platforms:
  amd64:

package-repositories:
  - type: apt
    ppa: amd-team/xrt

layout:
  /usr/share/lemonade-server:
    symlink: $SNAP/usr/share/lemonade-server
  /usr/share/hwdata:
    symlink: $SNAP/usr/share/hwdata
  /usr/share/misc/pci.ids:
    bind-file: $SNAP/usr/share/misc/pci.ids
  # Add layout entries so XRT's hardcoded absolute paths resolve to the snap's copies
  /usr/lib/x86_64-linux-gnu/libxrt_core.so.2:
    bind-file: $SNAP/usr/lib/x86_64-linux-gnu/libxrt_core.so.2.21.75
  /usr/lib/x86_64-linux-gnu/libxrt_coreutil.so.2:
    bind-file: $SNAP/usr/lib/x86_64-linux-gnu/libxrt_coreutil.so.2.21.75
  /usr/lib/x86_64-linux-gnu/libxrt_driver_xdna.so.2:
    bind-file: $SNAP/usr/lib/x86_64-linux-gnu/libxrt_driver_xdna.so.2.21.75
      
plugs:
  etc-systemd-system-daemon-override:
    interface: system-files
    write:
      - /etc/systemd/system/snap.lemonade-server.daemon.service.d

hooks:
  configure:
    plugs:
      - etc-systemd-system-daemon-override
  connect-plug-etc-systemd-system-daemon-override:
    plugs:
      - etc-systemd-system-daemon-override
  disconnect-plug-etc-systemd-system-daemon-override:
    plugs:
      - etc-systemd-system-daemon-override
  remove:
    plugs:
      - etc-systemd-system-daemon-override

slots:
  # Adds a pseudo content interface to allow clients to express their
  # runtime dependency on lemonade-server
  lemonade-server:
    interface: content
    content: foo
    read:
      - $SNAP/meta/snap.yaml

apps:
  metrics:
    command: bin/metrics
    plugs:
      - accel
      - home
      - removable-media
      - network
      - network-bind
      - opengl
      - process-control
      - hardware-observe
      - system-observe
  lemonade-server:
    command: usr/bin/lemonade-server
    plugs:
      - accel
      - home
      - removable-media
      - network
      - network-bind
      - opengl
      - hardware-observe
      - system-observe
    environment:
      LD_LIBRARY_PATH: "$SNAP/usr/share/lemonade-server:$SNAP/usr/lib/llamacpp/vulkan:$SNAP/usr/lib/x86_64-linux-gnu:$SNAP/lib/x86_64-linux-gnu:/var/lib/snapd/lib/gl${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
      PATH: "$SNAP/usr/bin:$PATH"
      HOME: "$SNAP_COMMON"
      LEMONADE_CACHE_DIR: "$SNAP_COMMON/cache/lemonade"
      FLM_MODEL_PATH: $SNAP_COMMON/flm/models
      FLM_CONFIG_PATH: $SNAP/usr/share/flm/model_list.json
      FLM_XCLBIN_PATH: $SNAP/usr/share/flm/xclbins
  daemon:
    command: bin/lemonade-server-wrapper serve
    daemon: simple
    install-mode: enable
    restart-condition: on-failure
    refresh-mode: restart
    plugs:
      - accel
      - home
      - removable-media
      - network
      - network-bind
      - opengl
      - process-control
      - hardware-observe
      - system-observe
    environment:
      LD_LIBRARY_PATH: "$SNAP/usr/share/lemonade-server:$SNAP/usr/lib/llamacpp/vulkan:$SNAP/usr/lib/x86_64-linux-gnu:$SNAP/lib/x86_64-linux-gnu:/var/lib/snapd/lib/gl${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
      PATH: "$SNAP/usr/bin:$PATH"
      HOME: "$SNAP_COMMON"
      LEMONADE_CACHE_DIR: "$SNAP_COMMON/cache/lemonade"
      LEMONADE_DISABLE_SYSTEMD_JOURNAL: 1
      FLM_MODEL_PATH: $SNAP_COMMON/flm/models
      FLM_CONFIG_PATH: $SNAP/usr/share/flm/model_list.json
      FLM_XCLBIN_PATH: $SNAP/usr/share/flm/xclbins
  flm:
    command: usr/bin/flm
    plugs:
      - accel
      - home
      - removable-media
      - network
      - network-bind
      - opengl
      - hardware-observe
      - system-observe
    environment:
      LD_LIBRARY_PATH: "$SNAP/usr/share/lemonade-server:$SNAP/usr/lib/llamacpp/vulkan:$SNAP/usr/lib/x86_64-linux-gnu:$SNAP/lib/x86_64-linux-gnu:/var/lib/snapd/lib/gl${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
      PATH: "$SNAP/usr/bin:$PATH"
      HOME: "$SNAP_COMMON"
      LEMONADE_CACHE_DIR: "$SNAP_COMMON/cache/lemonade"
      FLM_MODEL_PATH: $SNAP_COMMON/flm/models
      FLM_CONFIG_PATH: $SNAP/usr/share/flm/model_list.json
      FLM_XCLBIN_PATH: $SNAP/usr/share/flm/xclbins

parts:
  deps:
    plugin: nil
    build-packages:
      - curl
    stage-packages:
      - libgomp1
      - libatomic1
      - libcurl4t64
      - curl # for metrics
      - hwdata # PCI ID database for lspci device name resolution
      - pciutils # lspci for GPU detection
      - unzip # For extracting backends at runtime
      - libdrm-amdgpu1 # SD backends need this at runtime
      - libnuma1 # SD backends need this at runtime
    override-build: |
      set +u # For unbound variables
      # workaround for build.snapcraft.io builds
      # https://bugs.launchpad.net/bugs/1886861
      if [ -n "$http_proxy" ]; then
        export ELECTRON_GET_USE_PROXY=1
        export GLOBAL_AGENT_HTTP_PROXY="${http_proxy}"
        export GLOBAL_AGENT_HTTPS_PROXY="${http_proxy}"
      fi

      craftctl default
      # Download latest PCI ID database (hwdata package version is outdated)
      mkdir -p $CRAFT_PART_INSTALL/usr/share/misc
      curl -sL https://pci-ids.ucw.cz/v2.2/pci.ids -o $CRAFT_PART_INSTALL/usr/share/misc/pci.ids

  lemonade-server:
    plugin: cmake
    source: https://github.com/lemonade-sdk/lemonade.git
    cmake-parameters:
      - -DCMAKE_PREFIX_PATH=/usr
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DBUILD_WEB_APP=ON
    build-packages:
      - build-essential
      - g++
      - cmake
      - git
      - curl
      - libcurl4-openssl-dev
      - libssl-dev
      - zlib1g-dev
      - pkg-config
      - ninja-build
      - npm
    override-pull: |
      craftctl default
      VERSION=$(craftctl get version)
      if [ -z $VERSION ]; then
        VERSION=$(git describe --tags --abbrev=10)
        craftctl set version=$VERSION
      fi
      patch -p1 < $SNAPCRAFT_PROJECT_DIR/snap/local/patches/enable_npu.patch
    override-build: |
      craftctl default

  fastflowlm:
    plugin: cmake
    source: https://github.com/FastFlowLM/FastFlowLM.git
    source-subdir: src
    cmake-parameters:
      - -DCMAKE_PREFIX_PATH=/usr
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_XCLBIN_PREFIX=/usr/share/flm/xclbins
    build-packages:
      - build-essential
      - g++
      - cmake
      - git
      - curl
      - libcurl4-openssl-dev
      - libssl-dev
      - zlib1g-dev
      - pkg-config
      - ninja-build
      - libxrt-dev
      - libamdhip64-dev
      - libboost-program-options-dev
      - libboost-dev
      - libavcodec-dev
      - libavformat-dev
      - libavutil-dev
      - libdrm-dev
      - libfftw3-dev
      - libreadline-dev
      - libswresample-dev
      - libswscale-dev
      - uuid-dev
      - rustc-1.89
      - cargo-1.89
    stage-packages:
      - libamdhip64-5 # For ROCm support
      - libaom3
      - libavcodec60
      - libavformat60
      - libavutil58
      - libbluray2
      - libboost-program-options1.83.0
      - libcairo-gobject2
      - libcairo2
      - libchromaprint1
      - libcjson1
      - libcodec2-1.2
      - libdatrie1
      - libdav1d7
      - libfftw3-single3
      - libfontconfig1
      - libfribidi0
      - libgdk-pixbuf-2.0-0
      - libgme0
      - libgraphite2-3
      - libgsm1
      - libharfbuzz0b
      - libhwy1t64
      - libjpeg-turbo8
      - libjxl0.7
      - liblcms2-2
      - libmbedcrypto7t64
      - libmp3lame0
      - libmpg123-0t64
      - libnorm1t64
      - libogg0
      - libopenjp2-7
      - libopenmpt0t64
      - libopus0
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libpangoft2-1.0-0
      - libpgm-5.3-0t64
      - libpixman-1-0
      - librabbitmq4
      - librav1e0
      - librist4
      - librsvg2-2
      - libsharpyuv0
      - libshine3
      - libsnappy1v5
      - libsodium23
      - libsoxr0
      - libspeex1
      - libsrt1.5-gnutls
      - libssh-gcrypt-4
      - libsvtav1enc1d1
      - libswresample4
      - libswscale7
      - libthai0
      - libtheora0
      - libtwolame0
      - libudfread0
      - libva-drm2
      - libva-x11-2
      - libva2
      - libvdpau1
      - libvorbis0a
      - libvorbisenc2
      - libvorbisfile3
      - libvpl2
      - libvpx9
      - libwebp7
      - libwebpmux3
      - libx11-6
      - libx11-xcb1
      - libx264-164
      - libx265-199
      - libxau6
      - libxcb-dri3-0
      - libxcb-render0
      - libxcb-shm0
      - libxcb1
      - libxdmcp6
      - libxext6
      - libxfixes3
      - libxrender1
      - libxrt2
      - libxrt-npu2
      - libxvidcore4
      - libzmq5
      - libzvbi0t64
      - ocl-icd-libopencl1
    override-pull: |
      craftctl default
      patch -p1 < $SNAPCRAFT_PROJECT_DIR/snap/local/patches/preload_bundled_libraries.patch
    override-build: |
      export CARGO=/usr/bin/cargo-1.89
      export RUSTC=/usr/bin/rustc-1.89
      ln -sf /usr/bin/cargo-1.89 /usr/bin/cargo
      ln -sf /usr/bin/rustc-1.89 /usr/bin/rustc
      craftctl default
    prime:
      - usr/lib/*.so
      - usr/lib/*/*.so.*
      - usr/bin
      - usr/share/flm

  scripts:
    plugin: dump
    source: scripts/
    organize:
      lemonade-server-wrapper: bin/lemonade-server-wrapper
      metrics: bin/metrics
    override-prime: |
      craftctl default
      chmod +x $CRAFT_PRIME/bin/lemonade-server-wrapper
      chmod +x $CRAFT_PRIME/bin/metrics
